# Generated by Django 3.2.4 on 2021-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='lead_text',
            field=models.CharField(default='', max_length=254),
        ),
    ]
