# Generated by Django 3.2.4 on 2021-07-15 21:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_lead_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='categ',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='ideas.category'),
        ),
    ]
